# Generated by Django 5.1.4 on 2025-01-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='numberid',
        ),
    ]
